-- 1. Create tables

-- Profiles table to store user roles
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE,
  role TEXT DEFAULT 'staff' CHECK (role IN ('admin', 'manager', 'staff')),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Products table
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  brand TEXT,
  stock INTEGER DEFAULT 0,
  price NUMERIC DEFAULT 0,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Services table
CREATE TABLE IF NOT EXISTS public.services (
  ticket_id TEXT PRIMARY KEY,
  car_plate TEXT NOT NULL,
  customer TEXT,
  phone TEXT,
  issue TEXT,
  mechanic TEXT,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'In Progress', 'Completed')),
  parts_used JSONB DEFAULT '[]'::jsonb,
  labor_cost NUMERIC DEFAULT 0,
  total_cost NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Role permissions table
CREATE TABLE IF NOT EXISTS public.role_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL CHECK (role IN ('admin', 'manager', 'staff')),
  permission TEXT NOT NULL,
  UNIQUE(role, permission)
);

-- Transactions table for historical records
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id TEXT REFERENCES public.services(ticket_id) ON DELETE SET NULL,
  type TEXT NOT NULL CHECK (type IN ('Service', 'Sale')),
  customer_name TEXT,
  description TEXT,
  amount NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Setup Row Level Security (RLS)

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
CREATE POLICY "Users can update own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Products Policies
DROP POLICY IF EXISTS "Products are viewable by everyone." ON public.products;
CREATE POLICY "Products are viewable by everyone." ON public.products
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Managers and Admins can modify products." ON public.products;
CREATE POLICY "Managers and Admins can modify products." ON public.products
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('admin', 'manager')
    )
  );

-- Services Policies
DROP POLICY IF EXISTS "Services are viewable by everyone." ON public.services;
CREATE POLICY "Services are viewable by everyone." ON public.services
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "All staff can view/edit services." ON public.services;
CREATE POLICY "Anyone can view services." ON public.services
  FOR SELECT USING (true);

CREATE POLICY "Anyone can create services." ON public.services
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Staff can update services." ON public.services
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
    )
  );

-- Transactions Policies
DROP POLICY IF EXISTS "Transactions are viewable by everyone." ON public.transactions;
CREATE POLICY "Transactions are viewable by everyone." ON public.transactions
  FOR SELECT USING (true);

CREATE POLICY "Anyone can create transactions." ON public.transactions
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Only Admins and Managers can delete transactions." ON public.transactions;
CREATE POLICY "Only Admins and Managers can delete transactions." ON public.transactions
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('admin', 'manager')
    )
  );

-- 3. Functions & Triggers

-- Trigger to create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'staff')
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if it exists then create it
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Initial permissions (using ON CONFLICT to avoid duplicates)
INSERT INTO public.role_permissions (role, permission) 
VALUES
  ('admin', 'all'),
  ('manager', 'inventory.view'),
  ('manager', 'inventory.edit'),
  ('manager', 'services.view'),
  ('manager', 'services.edit'),
  ('staff', 'inventory.view'),
  ('staff', 'services.view'),
  ('staff', 'services.edit')
ON CONFLICT (role, permission) DO NOTHING;

-- 4. Storage Setup (Reference)
-- Manually create 'product-images' bucket in Supabase UI and set to Public.
